### PR TITLE
feat: grid layout added

### PR DESCRIPTION
**Pull request by purohitdheeraj**
this branch contains grid component

### CODE REVIEW

**Comment by JaswanthReddyPadala** [comment]
Use some better contrasting colors in place of light grey.
Apart from that UI is clean and Good Code ✔

**Review by JaswanthReddyPadala — CHANGES_REQUESTED** [review]
Use some better contrasting colors in place of light grey while showing examples.

**Review by srishtigautam21 — APPROVED** [review]
The UI looks great!!
Good to merge

**Review by JaswanthReddyPadala — APPROVED** [review]

**Review by JaswanthReddyPadala — APPROVED** [review]
Everything Looks Good Now, 
Simple look and components are very good ✅

**Pull request merged**
